function [time, data] = ImportTurbsimBin( filename )
%IMPORTTURBSIMBIN Import .bin file generated by turbsim.
%   [TIME, DATA] = IMPORTTURBSIMBIN( FILENAME ) imports FILENAME.
%
%   Input:
%       - filename: path to the file to load.
%   Outputs:
%       - time:     Nx1 vector of time values.
%       - data:     Nx13 matrix of wind data. Columns:
%                   [   U,   Uh,  Ut,    V,   W,  u',  v',  w',    u'w', ...
%                     m/s,  m/s, m/s,  m/s, m/s, m/s, m/s, m/s, (m/s)^2, ...
%                     ...    u'v',    v'w',     TKE,    CTKE ]
%                     ... (m/s)^2, (m/s)^2, (m/s)^2, (m/s)^2 ]
%
%   Note: due to the large size of the wind data, using simple arrays
%   instead of timetables is much more memory efficient (3x less memory
%   used).
%
%   See also FREAD.
%
%   Written: 2021/02/27, J.X.J. Bannwarth

    arguments
        filename (1,:) char { mustBeNonempty };
    end
    
    %% Read file contents
    fid = fopen( filename, 'r' );
    
    if fid <= 0
        error( 'Cannot open %s', filename );
    else
        raw = fread( fid, [14 inf], 'float32' );
        fclose( fid );

        time = raw(1,:)';
        data = raw(2:end,:)';
    end
end